import {NextPage} from "next";
import {Box} from "@mui/material";
import Head from "next/head";
import ResponsiveAppBar from "../navbar/navbar";
import Carousels from "./carousel";
import Footer from "../footer/footer";
import Product from "./product";
import {Props} from "framer-motion/types/types";

const HomePage: NextPage = (p : any) => {
    const data: Props = p
    return (
        <Box>
            <Head>
                <title>JN Wearzone</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
                />
            </Head>
            <ResponsiveAppBar/>
            <Box sx={{marginTop: 8}}>
                <Carousels/>
            </Box>

            <Box style={{marginTop: 10, marginBottom : 10}}>
                <Product{...data}/>
            </Box>
            <Footer/>

        </Box>
    )
}
export default HomePage